name: eslint

on: 
  push:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation des dépendances
        run: yarn --cwd ./front
      - name: Lintage
        run: yarn --cwd ./front eslint . --ext .js
